Description: 'Creates an Ubuntu EC2 instance with a web server installed.'

Parameters:
  InstanceName:
    Type: String
    Default: 'ShellInstance'
    Description: 'Name of EC2 Instance'
  KeyName:
    Type: String
    Default: 'ShellInstanceKeyPair'
    Description: 'Name of EC2 Key Pair'
  SecurityGroupName:
    Type: String
    Default: 'ShellInstanceSecurityGroup'
    Description: 'Name of EC2 Security Group'

Resources:
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'aws/service/ami-amazon-linux-latest/amzn-hvm-x86_64-gp2'
      InstanceType: 't2.micro'
      BlockDeviceMappings:
        Ebs:
          VolumeSize: 30
      KeyName: !Ref 'KeyName'
      Tags:
      - Key: 'Name'
        Value: !Ref 'InstanceName'

  KeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyFormat: 'pem'
      KeyName: !Ref 'KeyName'
      KeyType: 'rsa'

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Ref 'SecurityGroupName'
      SecurityGroupIngress:
      - IpProtocol: 'tcp'
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0