Description: 'Creates an Ubuntu EC2 instance with a web server installed.'

Parameters:
  InstanceName:
    Type: String
    Default: 'ShellInstance'
    Description: 'Name of EC2 Instance'
  KeyName:
    Type: String
    Default: !Join [ '', [ !Ref InstanceName, 'KeyPair' ] ]
    Description: 'Name of EC2 Key Pair'

Resources:
  GetKey:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyFormat: 'pem'
      KeyName: !Ref 'KeyName'
      KeyType: 'rsa'

  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'aws/service/ami-amazon-linux-latest/amzn-hvm-x86_64-gp2'
      InstanceType: 't2.micro'
      BlockDeviceMappings:
        Ebs:
          VolumeSize: 30
      KeyName: !Ref 'KeyName'
      Tags:
        - Key: 'Name'
          Value: !Ref 'InstanceName'